name: Android Release (signed)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.java'
      - '**.gradle'
      - '**.gradle.kts'
      - 'app/src/**'
      - '.github/workflows/android-release.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Download Gradle 8.7
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
          unzip -q gradle.zip
          echo "$GITHUB_WORKSPACE/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Recreate keystore from secret
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > release.keystore

      - name: Build release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: >
          gradle -v && gradle
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/release.keystore
          -Pandroid.injected.signing.store.password="${KEYSTORE_PASSWORD}"
          -Pandroid.injected.signing.key.alias=seekerrex87
          -Pandroid.injected.signing.key.password="${KEY_PASSWORD}"
          assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MCContentManagerPro-release
          path: '**/build/outputs/apk/release/*.apk'
